### ISSUE TITLE
Benchmark improvements

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest-iac#137]
**Issue summary**

- [x] Peak memory usage. Can be measured with `/usr/bin/time -v`.
- [ ] Validation time in a recent snapshot. Lotus doesn't have this functionality but we can fairly easily add it.
- [ ] Time to migrate network versions.
- [ ] Time to export a snapshot. Lotus requires more than 64GiB of memory to export a mainnet snapshot. Find a way to set a memory limit. If that's too difficult then we can just measure calibnet export.
- [ ] Time to compute the state of a single tipset (using `lotus state compute-state`).
- [ ] Use `lotus-shed` to benchmark individual functions without running the lotus-daemon.
- [ ] Use published Docker images instead of building Lotus on our own https://github.com/ChainSafe/forest-iac/issues/143
- [ ] [Create common error handler](https://github.com/ChainSafe/forest/pull/2367#discussion_r1195390109).
- [ ] [Check preconditions before running script (enough disk space and `ulimit -n` is correctly set).](https://github.com/ChainSafe/forest/pull/2367#discussion_r1200295926)
- [ ] [Delete cloned git repos at the end of script instead of after each client run.](https://github.com/ChainSafe/forest/pull/2367#discussion_r1200311414) (not applicable if/when the task to use published Docker images above is completed)
- [ ] [Investigate and fix issue with missing gems when using `bundle install`.](https://github.com/ChainSafe/forest/pull/2367#issuecomment-1558977266)
- [ ] Other misc improvements/optimizations (e.g., [long form command line options](https://github.com/ChainSafe/forest/pull/2367#discussion_r1196605001), [modify `private` module designations](https://github.com/ChainSafe/forest/pull/2367#discussion_r1195387339), [replace erroneous references to `heights` with `epochs` or `tipsets`](https://github.com/ChainSafe/forest/issues/2925)).
- [ ] Ensure snapshot is deleted (only if downloaded) after a successful run (we only seem to be deleting a downloaded snapshot in case of an error).

**Other information and links**

Migrated tasks from analogous [issue in Forest repo](https://github.com/ChainSafe/forest/issues/2683).

**Comment by jdjaustin** [comment]
Currently working on the task to create a common error handler and simultaneously improving error handling (currently we suppress detailed errors).

**Comment by LesnyRumcajs** [comment]
The CPU usage should also be added to the result of each action.

**Comment by elmattic** [comment]
We should be able to import snapshots in their compressed form for both clients now (this will save us some space on the droplet).
