### ISSUE TITLE
Automate Comparison of Checksums for Forest and Lotus Snapshots

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest-iac#144]
**Issue summary**

We would like to verify that Forest and Lotus snapshots continue to match byte-for-byte as part of CI checks. The steps to accomplish this are as follows:

1. Download the Lotus snapshot.
2. Import it into Forest.
3. Export the snapshot at height specified in Lotus snapshot.
4. Compare the checksums. 

**Other information and links**

Link to original issue from Forest repo: https://github.com/ChainSafe/forest/issues/2559

**Comment by lemmih** [comment]
It doesn't matter where the check happens as long as it happens. So that you know, we already check that our calibnet snapshots match byte-for-byte. This issue is only for mainnet snapshots.

**Comment by lemmih** [comment]
Figuring out a sensible way of verifying our mainnet snapshots is 90% of this issue.

**Comment by lemmih** [comment]
> > It doesn't matter where the check happens as long as it happens. So that you know, we already check that our calibnet snapshots match byte-for-byte. This issue is only for mainnet snapshots.
> 
> @lemmih okay, but can i get a reference to where this is done for calibnet?

Here it is: https://github.com/ChainSafe/forest/blob/fbe13ff2da46ab68a0d5021a708e638246dbfc08/scripts/tests/forest_cli_check.sh#L40

**Comment by lemmih** [comment]
Cons:
- The cost of a droplet is fairly steep for this task this simple.
- The uploaded snapshots are not directly verified.
- You export from `forest-tool` rather than a running forest node. In an ideal world, there would be no difference between `forest-tool` and a forest node, but we may not live in an ideal world.

The cons outweigh the pros of this approach, imo.

**Comment by LesnyRumcajs** [comment]
> The cost of a droplet is fairly steep for this task this simple.
We could use cronjob on Github Actions. This would be free, if we go with calibnet snapshots.

That said, this approach doesn't check Forest snapshots at all. `forest-cli snapshot export` could be completely broken (e.g., not save the files at all) yet this would pass.

**Comment by LesnyRumcajs** [comment]
My remark about GHA was only applicable to testing the `forest-tool` feature, which we don't really want.

We could, most likely, have a job that does the following (and it wouldn't require a running Lotus node.
1. Download the latest Lotus snapshot. Note the epoch at which it was exported.
2. Import it to Forest. Sync to head. (I believe it's a requirement on our side, unless something changed). No garbage collection is enabled.
3. Export at height of the Lotus snapshot.

We could do it with calibnet-only and use GHA cronjobs. Is it feasible @lemmih ?

**Comment by LesnyRumcajs** [comment]
> forest-tool archive export and forest node export should have no difference

That's a bit wishful. If @lemmih agrees, though, I can live with that.

**Comment by lemmih** [comment]
The verification we already have in GHA is sufficient for calibnet. For mainnet, the pros and cons are different. If we're paying $100/month for a droplet, then a quick-and-dirty check isn't worth it.

**Comment by LesnyRumcajs** [comment]
Then let's do it properly as outlined in the issue description. If not, let's close this issue.

**Comment by lemmih** [comment]
> > Then let's do it properly as outlined in the issue description. If not, let's close this issue.
> 
> Fine, we will do as stated in the outline

That will cost us tens of thousands of dollars per month. As I wrote above, figuring out a sensible way of verifying our snapshots is 90% of this issue, and we still haven't done that part yet. Don't start implementing anything before you have an approved plan.

**Comment by lemmih** [comment]
> > That will cost us tens of thousands of dollars per month. As I wrote above, figuring out a sensible way of verifying our snapshots is 90% of this issue, and we still haven't done that part yet. Don't start implementing anything before you have an approved plan.
> 
> Noted. what about the possibility of running on `archive` or `fuzzy`?

They are not capable of exporting a Lotus snapshot.

**Comment by LesnyRumcajs** [comment]
Why would it cost us so much? We'd only download the latest Lotus snapshot, not generate it ourselves. This approach, sadly, relies on the assumption that FilOps don't use Forest to generate snapshot, which may or may not change in the future.

**Comment by lemmih** [comment]
> Why would it cost us so much? We'd only download the latest Lotus snapshot, not generate it ourselves. This approach, sadly, relies on the assumption that FilOps don't use Forest to generate snapshot, which may or may not change in the future.

Then we're back at not validating the snapshots that we're actually uploading. This thread is getting way too confusing for me. Many suggestions have been aired, and tracking which solution is being discussed is difficult.

Let's shelve this issue for now unless someone puts forward a concrete solution with strong arguments for why the pros outweigh the cons.
