### ISSUE TITLE
Gentle sync check recovery

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#163]
**Issue summary**

Introduced in https://github.com/ChainSafe/forest-iac/pull/152, the database cleanup is harsh. Such an operation should not be performed on a living service which dies in screaming agony for several hours afterwards.

It should be as follows:
1. Stop the service
2. Clean the database
3. Start the service
4. Re-start the test for that service.

This most likely requires splitting `forest-tester` into two separate services, `forest-tester-mainnet` and `forest-tester-calibnet` so that one doesn't affect another.

**Other information and links**

**Comment by lemmih** [comment]
We can shutdown Forest through the cli. Will deleting the database and then shutting down Forest cause the service to re-start?

**Comment by LesnyRumcajs** [comment]
I'd like to avoid removing the database on a living service, it's undefined behaviour to my understanding. As a result, it could crash and then the CLI command to shutdown would fail.

I'd instead use `docker compose stop/start` to ensure everything is in order.

**Comment by LesnyRumcajs** [comment]
It's been working fine as is.
