### ISSUE TITLE
Research: Joining car.zst files in CloudFlare Worker

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest-iac#182]
**Issue summary**

Can `.forest.car.zst` files be joined in a worker? It would require stripping the header frame from all but the first file. Can multiple javascript streams be efficiently joined?

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@lemmih I guess we no longer plan to do it?

**Comment by lemmih** [comment]
Yeah, no need for this anymore.
