### ISSUE TITLE
Fetch the metrics snapshot before killing the daemon and upload

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest-iac#20]
**Issue summary**

It could be useful to see the metrics snapshot in the sync check report, together with the daemon log.

We can also do some checks on the metrics log, e.g. process memory usage, open fd, all libp2p protocols have successful message exchange, etc

**Other information and links**

endpoint: http://localhost:6116/metrics

**Comment by LesnyRumcajs** [comment]
Snapshot service discontinued in favour of the ChainSafe infra snapshot service.
