### ISSUE TITLE
snapshot endpoint requires trailing slash

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest-iac#286]
```console
$ wget https://forest-archive.chainsafe.dev/latest/calibnet
--2023-10-02 14:06:57--  https://forest-archive.chainsafe.dev/latest/calibnet
Resolving forest-archive.chainsafe.dev (forest-archive.chainsafe.dev)... 172.67.172.192, 104.21.30.105, 2606:4700:3031::ac43:acc0, ...
Connecting to forest-archive.chainsafe.dev (forest-archive.chainsafe.dev)|172.67.172.192|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-02 14:06:58 ERROR 404: Not Found.
```

```console
$ wget https://forest-archive.chainsafe.dev/latest/calibnet/
--2023-10-02 14:07:16--  https://forest-archive.chainsafe.dev/latest/calibnet/
Resolving forest-archive.chainsafe.dev (forest-archive.chainsafe.dev)... 172.67.172.192, 104.21.30.105, 2606:4700:3031::ac43:acc0, ...
Connecting to forest-archive.chainsafe.dev (forest-archive.chainsafe.dev)|172.67.172.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2425491337 (2.3G) [application/zstd]
Saving to: **'index.html'**
```

To be clear
```diff
+ $ wget https://forest-archive.chainsafe.dev/latest/calibnet
- $ wget https://forest-archive.chainsafe.dev/latest/calibnet/
+ HTTP request sent, awaiting response... 404 Not Found
- HTTP request sent, awaiting response... 200 OK
```

I'd also prefer if it didn't download as `index.html` - using redirects would give us this behaviour.

**Comment by lemmih** [comment]
> I'd also prefer if it didn't download as `index.html` - using redirects would give us this behaviour.

It's a feature of `wget`. I'd rather tell people to use `--trust-server-names` or `aria2c` than add a redirect.

**Comment by LesnyRumcajs** [comment]
This doesn't work, sadly. Even though it worked in `--dev`, outside of it, it produces 404s.

```
❯ wget https://forest-archive.chainsafe.dev/latest/calibnet
--2023-11-02 16:53:02--  https://forest-archive.chainsafe.dev/latest/calibnet
...
HTTP request sent, awaiting response... 404 Not Found
2023-11-02 16:53:02 ERROR 404: Not Found.
```

**Comment by lemmih** [comment]
> This doesn't work, sadly. Even though it worked in `--dev`, outside of it, it produces 404s.
> 
> ```
> ❯ wget https://forest-archive.chainsafe.dev/latest/calibnet
> --2023-11-02 16:53:02--  https://forest-archive.chainsafe.dev/latest/calibnet
> ...
> HTTP request sent, awaiting response... 404 Not Found
> 2023-11-02 16:53:02 ERROR 404: Not Found.
> ```

I forgot to add a workflow for auto-deploying workers. If you didn't manually deploy the new code then the old code is still running on production.

**Comment by LesnyRumcajs** [comment]
Ah, I thought it's automagic. How to do it manually?

**Comment by lemmih** [comment]
> Ah, I thought it's automagic. How to do it manually?

`wrangler deploy` I think.
