### ISSUE TITLE
Cleanly upgrade terraform cli version and provider configurations

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest-iac#299]
**Issue summary**

**Task summary**

Cleanly upgrade terraform  version and provider configurations

**Acceptance Criteria**

**Other information and links**

**Comment by LesnyRumcajs** [comment]
The error rather comes from `s3` incompatibility. It should be fixed in `1.6.3` by adding `skip_s3_checksum` to the `backend`.

https://github.com/hashicorp/terraform/issues/34053
