### ISSUE TITLE
Slack messages not attaching to the thread

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#31]
**Describe the bug**

This started happening today (14.02.23) for no apparent reason, with no update whatsoever. The Slack attachments got posted in the channel instead of the thread. Not sure where the bug lies - our logic, ruby wrapper or slack api.

https://github.com/ChainSafe/forest-iac/blob/d8e8d9e1247679015554c6bfcf36543aa6d06f2f/scripts/ruby_common/slack_client.rb#L26

https://api.slack.com/methods/chat.postMessage#arg_thread_ts

It seems to be okay. There may be an edge case I am not aware of.

**To Reproduce**
No idea how to reproduce it for now.

**Expected behaviour**

All the attachments and comments are *always* sent to the parent thread.

**Screenshots**

![image](https://user-images.githubusercontent.com/9642092/218672050-5d7f8ada-197f-4705-b6a0-5e3f9cc0356d.png)

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Rust version(e.g. `rustc --version`)
 - Branch/commit d8e8d9e

**Other information and links**

**Comment by hanabi1224** [comment]
Not sure if it's related to this issue, I notice that ruby dependency versions are not specified in Dockerfile, how about including `Gemfile.lock` in the source tree and use `bundle install` to make sure dependency versions are fixed

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Yeah, it may be a good practice to avoid potential regressions. That being said, the root issue was most likely a regression on the Slack API side. I expect (hope) that the notifications will work just fine today. https://status.slack.com/2023-02/f735b7262fd0efc2

**Comment by LesnyRumcajs** [comment]
Confirming it has auto-resolved automagically. The culprit was the Slack API outage. 
![image](https://user-images.githubusercontent.com/9642092/218999669-2108c4dd-0e47-4c98-b0ed-39fe854f9440.png)
