### ISSUE TITLE
Hosted snapshots should include their respective hashes

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#370]
**Issue summary**

This is an umbrella issue for all snapshots hosted in Cloudflare. If someone downloads 20 TiB worth of snapshots, they should be able to verify successful and correct download via digests.

This includes:
- [ ] Lite snapshots (and their automatic generation, once it happens),
- [ ] Diff snapshots (and their automatic generation, once it happens),
- [x] Latest snapshots

For both mainnet and calibration network.

The standard approach is to use `sha256sum`. Unless something has changed, Forest can generate the checksum file independently when exporting a snapshot. I'm not sure what the status of this feature outside of the export command is.

**Other information and links**

**Comment by samuelarogbonlo** [comment]
@LesnyRumcajs, my proposed solution is to write a one off script will download or regenerate the current snapshots (both lite and diff), create a shasum file for them, and upload everything to R2. After that,  we can update [this](https://github.com/ChainSafe/forest-iac/pull/428) when @sudo-shashank is done to include the SHA sum in the process of generating and uploading archival snapshots. For the latest snapshot, we can update the snapshot service to also generate shasums and upload. 

Question: should we update the Cf code to also download the `shasum` when the snapshot link is hit

**Comment by LesnyRumcajs** [comment]
1. It's not needed to download the lite and diff snapshots (at least most of them) - they are in majority on archie.
2. What's the point of regenerating the snapshots? The snapshots won't change, so only corresponding shasum files need to be uploaded.

> Question: should we update the Cf code to also download the shasum when the snapshot link is hit
No. The vast majority of people won't use them.

**Comment by LesnyRumcajs** [comment]
Migrated to Infrastructure repo.
