### ISSUE TITLE
Migrate Forest node services to Terragrunt

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#373]
**Issue summary**

Follow-up of https://github.com/ChainSafe/forest-iac/pull/354

Given how snapshot service was migrated, do the same for the filecoin-node services:
- [forest-mainnet](https://github.com/ChainSafe/forest-iac/tree/3e1b9c3665dc707d4a54357174bb95a409994021/terraform/forest-mainnet)
- [forest-calibnet](https://github.com/ChainSafe/forest-iac/tree/3e1b9c3665dc707d4a54357174bb95a409994021/terraform/forest-calibnet)
- [filecoin-node](https://github.com/ChainSafe/forest-iac/tree/3e1b9c3665dc707d4a54357174bb95a409994021/terraform/modules/filecoin_node)

Some basic form of NR alarm should be included (or added in a follow-up PR to keep things small).

**Other information and links**

**Comment by samuelarogbonlo** [comment]
@LesnyRumcajs @aatifsyed should this not be marked as closed ?.

**Comment by LesnyRumcajs** [comment]
Hm, almost. There's still https://github.com/ChainSafe/forest-iac/issues/413 to do, but it can live as a separate thing. I'll do some cleanup today to close this.
