### ISSUE TITLE
Consider using hosted monitoring

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest-iac#78]
**Issue summary**

Hosting our own monitoring services is troublesome and expensive. It may be possible to just pay for the service.

Have a look at:

- DataDog
- NewRelic
- Grafana Cloud
- Other?

What are our requirements?

- Consume logs
- Health alerts for hosts (CPU, responsiveness, disk space, etc)
- Consume prometheus data
- Other?

**Other information and links**

**Comment by LesnyRumcajs** [comment]
From my experience with NewRelic it ticks all the boxes for requirements (I've been using it mostly with Kubernetes, though). You could get really decent dashboards and alarms with NRQL. Another nice thing about it was the [instrumentation](https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/custom-instrumentation/) and [telemtry](https://github.com/newrelic/newrelic-telemetry-sdk-rust#readme). This could be used to monitor how fast a e.g., tipset validation executes, with historical data. This would let us spot performance regressions easily.

**Comment by lemmih** [comment]
We've decided to go with NewRelic.
