### ISSUE TITLE
Verify snapshot before uploading

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#85]
**Issue summary**

It appears that it is possible for Forest to generate invalid snapshots. Even though the root issue is yet to be discovered, we should still be able to prevent uploading invalid snapshots and marking them as `latest`.

Steps:
- [ ] Verify the snapshot before it is uploaded to DO Spaces - note that `forest-cli snapshot validate` may try to load the snapshot in a temp folder. We need a way to specify where that temp folder should be located.
- [ ] If the snapshot is invalid, move it to a special directory (also in DO Spaces). Zip it with logs included. This should help to find the root cause in the Forest itself.

**Other information and links**

Surfaced in https://github.com/ChainSafe/forest/actions/runs/4984013893/jobs/8921930276

**Comment by LesnyRumcajs** [comment]
It seems it's happening quite often, as @elmattic noted. We might want to prioritise it a bit.

**Comment by lemmih** [comment]
Where did @elmattic note this?

**Comment by elmattic** [comment]
@lemmih I noticed this [here](https://github.com/ChainSafe/forest/actions/runs/5177511064/jobs/9327922621?pr=2740).

**Comment by lemmih** [comment]
That is quite strange. The snapshot service always uses the most recent snapshot to generate the following snapshot. That means the snapshot couldn't have been completely broken.

**Comment by lemmih** [comment]
Things are not great. I cannot re-validate the tipsets in `forest_snapshot_calibnet_2023-06-05_height_621698.car` but the snapshot file isn't broken in any way I can detect:

Failure to re-validate:
```
2023-06-06T07:30:50.671017Z  INFO forest_genesis: Validating imported chain from height: 621498    
Error: Failed miserably while importing chain from snapshot /home/lemmih/.local/share/forest/snapshots/calibnet/forest_snapshot_calibnet_2023-06-05_height_621698.car: Serialization error for Cbor protocol: Mismatch { expect_major: 4, byte: 165 }
```

But snapshot validates:
```
$ ./target/release/forest-cli --chain calibnet snapshot validate ~/.local/share/forest/snapshots/calibnet/forest_snapshot_calibnet_2023-06-05_height_621698.car
✔ This will result in using approximately 2326 MB of data. Proceed? · yes
2023-06-06T07:31:31.442320Z  INFO forest_genesis: Initialized genesis: BlockHeader: Cid(bafy2bzacecyaggy24wol5ruvs6qm73gjibs2l2iyhcqmvi7r7a4ph7zx3yqd4)    
2023-06-06T07:31:31.442795Z  INFO forest_utils::net::download: Loading /home/lemmih/.local/share/forest/snapshots/calibnet/forest_snapshot_calibnet_2023-06-05_height_621698.car, is_zstd_compressed: false    
Importing snapshot 2.27 GB / 2.27 GB [====================================================] 100.00 % 320.52 MB/s 2023-06-06T07:31:39.063001Z  INFO forest_utils::db: Buffered write completed: total entries: 2318512, total size: 2.42GB, took: 7s    
Validating tipsets: 621698 / 621698 [======================================================] 100.00 % 40636.32/s Snapshot is valid
```

Adding a validation step to the snapshot-uploader wouldn't solve this problem.

**Comment by lemmih** [comment]
We either need to re-validate the newly generated snapshot OR extend `snapshot verify` with more checks.

**Comment by LesnyRumcajs** [comment]
What checks does `snapshot verify` not do when compared to a regular snapshot import  when running the node?

**Comment by lemmih** [comment]
> What checks does `snapshot verify` not do when compared to a regular snapshot import when running the node?

It only checks if the IPLD data is valid with no broken links. It doesn't parse the Filecoin-specific data structures.

**Comment by lemmih** [comment]
The underlying problem with the snapshot files went away on its own. It may have been related to how we were writing the CAR files. No invalid snapshot files have been generated in weeks.

Snapshot files are still not deeply validated before they're uploaded. Doing so would take too much time. I say we keep this issue open until we have found a feasible way to ensure the snapshots are valid. Maybe we should bite the bullet and deeply validate them.

**Comment by LesnyRumcajs** [comment]
Let's keep this open and tackle this once an issue appears again that is not caught by anything else. No point in wasting time and resources for now.

**Comment by LesnyRumcajs** [comment]
All is good now. Will re-open if the issue appears again.
