### ISSUE TITLE
Run Daily Benchmark Script Automagically

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest-iac#92]
**Issue summary**

Tasks for running benchmark script automatically:
- [X] configure a droplet (detailed requirements listed below) that is automatically created daily and destroyed (destruction can either be triggered by the script or workflow, we may need to evaluate which would be best) after successful run of the script
- [X] move the benchmark script to `forest-iac` and deploy
- [X] configure droplet to export the CSV results to a location off-droplet
- [X] configure alerts if the script fails for any reason (including during setup and installation of pre-reqs)
- [x] test that everything works properly (creation/deletion of droplet, script runs or alerts on failure, CSV exports correctly)

**Other information and links**

We will need to automatically: create the droplet, install the pre-reqs as outlined in the `README.md`, run the benchmarks script (currently in the Forest repo [here](https://github.com/ChainSafe/forest/blob/44e150874293fb7f42d74681268678c8251d78a9/scripts/benchmark_db/bench.rb), needs to be moved to `forest-iac` as part of PR for this issue), export the CSV that is generated (possibly where our snapshots go?), and destroy the droplet upon successful run (or alert on failure without destroying the droplet to allow troubleshooting of the issue).

We need a machine with a dedicated CPU so the results are reproducible. A 320GB disk was sufficient to run the mainnet tests, but we may need more storage in the near future as features are added to the script. We have tested on both Ubuntu and Fedora droplets; as most of the existing IAC infra is Ubuntu, we can go with Ubuntu if we want to be consistent.

**Comment by lemmih** [comment]
Blocked by this issue: https://github.com/ChainSafe/forest/issues/2208
